{% set name = "timm" %}
{% set version = "1.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90ccf07894d6ae38259b7aa7c94d683002f5e360fd43471c84f9da6c3afb8a0d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm

    # The follow might also be needed
    - pdm-backend
  run:
    - python >={{ python_min }}
    - pytorch >=1.7
    - torchvision
    - pyyaml
    - huggingface_hub
    - safetensors >=0.2

test:
  imports:
    - timm
    - timm.data
    - timm.loss
    - timm.models
    - timm.models.layers
    - timm.optim
    - timm.scheduler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rwightman/pytorch-image-models
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: (Unofficial) PyTorch Image Models
  doc_url: https://pypi.org/project/timm/
  dev_url: https://github.com/rwightman/pytorch-image-models

extra:
  recipe-maintainers:
    - deepsworld
    - ndmaxar
    - oblute
    - rluria14
    - thewchan
